library(covr)
cov <- package_coverage()
print(cov)
zero_coverage(cov)
report(cov, file = file.path("/workdir/tests/coverage-report.html"), browse = FALSE)
codecov(coverage = cov, token = "ec444c0b-c51d-4cb1-b305-7fec9c4ebc6b")
